[tool.poetry]
name = "agent"
version = "0.1.0"
description = ""
authors = ["Kevin Sakai <kevinsakai@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
uagents = "^0.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
